# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish VSCODE Extension

on:
  release:
    types: [created]
  push:
    branches: [development]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: |
          cd vscode-extension-template
          npm ci
          npm run build --if-present

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: |
          cd vscode-extension-template
          npm ci
      - run: |
          cd vscode-extension-template
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  publish-marketplace:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Install the dependencies
        run: |
          cd vscode-extension-template
          npm ci

      - name: Install vsce
        run: |
          cd vscode-extension-template
          npm i -g vsce

      - name: Publish
        run: |
          cd vscode-extension-template
          vsce publish -p ${{ secrets.VSCE_PAT }}